### ISSUE TITLE
check_folder_anonymize always returning False

### ISSUE THREAD

**Issue by rbonicel** [cati-neuroimaging/deidentification#47]
Hi all,

On my non-anonymized dicom folder, I run the `anonymizer.check_folder_anonymize` function, and it returns False, which is alright. 
I then perform the `anonymizer.anonymize` with `forced_values={(0x0010, 0x0010): subject_name`, which works (checked with MRIConvert) to rewrite the tags of the same dicom files. 
But when i run the `anonymizer.check_folder_anonymize` function again, it still yields False. I only feed the dicom_folder parameter as the others are all optional, but should I be feeding a config_profile or anonymous ?
I thought that is I don't feed any of the optional parameters, the function will perform a check on "common" tags, don't know if I'm mistaken.

That last parameter is a bit enigmatic, also.

I'm using the 1.1.2 version of the package.

Thanks for your help

Robin

**Comment by Hboni** [comment]
Hello, if you want to check anonymization after using `anonymizer.anonymize`, you must use exactly the same parameters in `anonymizer.check_folder_anonymize`, it means that you also need to add `forced_values={(0x0010, 0x0010): subject_name}`.
If you do not do it, it will check this tag and see that it is not well anonymized. By default, the tag (0x0010, 0x0010) is empty after anonymization.

For the last parameter, you're right, there is no explanation/documentation, my bad. It allows anonymizer to return error without any message about filename anonymized. This option can be used to avoid pathnames to stay in log files.

Hope it helps

**Comment by rbonicel** [comment]
Hi, 

Sorry about the delay. I completed the parameters in the `anonymizer.check_folder_anonymize` according to your comment, and it gave me `True` when expected. 

Last small question related to the `'D' De-identification Action Codes`. When a date is concerned, such as `(0008, 0022) Acquisition Date`, can I change the dummy value used in order to keep the real year of the dicom tag, in order to go from, for example, `20231205` to `20230101` ?
There are various date tags in the dicom, and they don't all need the same replacement values in the anonymization process. 

For now, the dummy value in place is `20000101`, which is not convenient.

Thanks a lot.

**Comment by Hboni** [comment]
Hi,

Happy that last message helps. For your question about deidentification of date, using action **D** forces date to be equal to 19700101 (I'm surprised you got 20000101!). There is no mechanism that allows to specify which dummy value you want for a specific Tag type.
Regarding actions codes, as you tried, **C** might be a better alternative to get less dummy values. But this clean action is not implemented, as you point out, because this action can be tricky, for other Tags type (eg. Tags with free text might be filtered to only keep relevant informations, as described here : https://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_E.3.5)

I see two options for your problem:
- if you know exactly which tags you want to keep, you can specify manually the values that you want for those tags (using the `forced_values` parameter, eg. `forced_values={(0x0008, 0x0022): "20230101"}`)
- if you want to specify a specific value for date tags, you can modify code to have the date you want (but it may be the same for all the DICOMS, if you want to have at least the same year, it may be a bad choice)  https://github.com/cati-neuroimaging/deidentification/blob/15106d898aa5ac95a55951b16a419c98b99fb646/deidentification/anonymizer.py#L403

I do not recommend the second solution as you may not be able to reproduce the deidentification if you remove your modification.

**Comment by rbonicel** [comment]
I'm on v1.2.7 of the tool, and in `anonymizer.py` ,I found : 
![Screenshot from 2024-01-05 14-57-17](https://github.com/cati-neuroimaging/deidentification/assets/48990813/3db13e78-e16e-4d1e-b5d7-01853069df37)

I was about to ask the team if they really need he Phlips' style anonymization on the date tags, or if I can use the same dummy value provided by your code, which would be fine by me and less troublesome, as you pointed out.

I consider the issue closed, thanks for the help.

**Comment by Hboni** [comment]
The default date is 19700101 since version 1.2.4, thanks to Dimitri in #41 .
You might be in anterior version of the code, or maybe you have modification of the code locally.

**Comment by rbonicel** [comment]
Indeed. My `deidentification` package was not properly updated inside my poetry venv. It's fixed now and I'm using the `1.2.7` version with the correct default date value.
